### ISSUE TITLE
Failing on 0.12.1 from source

### ISSUE THREAD

**Issue by vonpupp** [ansiblebit/wkhtmltopdf#10]
Greetings,

I have the following playbook:
```
---
- hosts: localhost
  user: root
  vars:
    git_version: 0.12.1
    wkhtmltopdf_build: git
    wkhtmltopdf_installation: source

    # wkhtmltopdf_installation: package
    # wkhtmltopdf_version: 0.12.1

  roles:
    - role: ansiblebit.git
    - role: ansiblebit.wkhtmltopdf
```

It should work but it is failing with the following message:
```
TASK [ansiblebit.git : installation | download source tarball] ********************************************************************************************************************
 [WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: (task_git_installed is defined and task_git_installed.rc != 0) or
(task_git_version is defined and task_git_version.stdout.find("git version {{ git_version }}") == -1)

fatal: [localhost]: FAILED! => {"changed": false, "dest": "/usr/local/src", "failed": true, "gid": 0, "group": "root", "mode": "0755", "msg": "Request failed", "owner": "root", "response": "HTTP Error 404: Not Found", "size": 4096, "state": "directory", "status_code": 404, "uid": 0, "url": "https://codeload.github.com/git/git/tar.gz/v0.12.1"}
	to retry, use: --limit @/home/av/abba.project/deploy.ansible/playbook-wkhtmltopdf.retry

PLAY RECAP ************************************************************************************************************************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=1
```

The URL seems to be invalid (404)

Any ideas on how to proceed, please? Thanks!

**Comment by steenzout** [comment]
@vonpupp I'll look at it tonight.

**Comment by steenzout** [comment]
this is a problem with the `ansiblebit.git` role.

**Comment by steenzout** [comment]
@vonpupp you have the wrong `git_version`.

you've set it to `0.12.1` and it needs to be a value from the git [releases](https://github.com/git/git/releases) page.

you confused the value for `wkhtmltopdf_version: 0.12.1` with the value for `git_version`.

**Comment by steenzout** [comment]
try this:
```
---
- hosts: localhost
  user: root
  vars:
    git_version: 2.13.0
    wkhtmltopdf_build: git
    wkhtmltopdf_installation: source
    wkhtmltopdf_version: 0.12.1

  roles:
    - role: ansiblebit.git
    - role: ansiblebit.wkhtmltopdf
```

**Comment by vonpupp** [comment]
I thought of that possibility also, thanks for your explanation @steenzout.

I have tried it on Ubuntu Xenial and I still have a problem:
```
TASK [ansiblebit.wkhtmltopdf : build | setup chroot environment] ******************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "python2.7 scripts/build.py setup-schroot-generic", "delta": "0:00:00.045309", "end": "2017-05-31 21:20:57.195224", "failed": true, "rc": 2, "start": "2017-05-31 21:20:57.149915", "stderr": "", "stderr_lines": [], "stdout": "Usage: scripts/build.py <target> [-clean] [-debug]\n\nThe supported targets are:\n* centos5-amd64\n* centos5-i386\n* centos6-amd64\n* centos6-i386\n* mingw-w64-cross-win32\n* mingw-w64-cross-win64\n* msvc-winsdk71-win32\n* msvc-winsdk71-win64\n* msvc2008-win32\n* msvc2008-win64\n* msvc2010-win32\n* msvc2010-win64\n* msvc2012-win32\n* msvc2012-win64\n* msvc2013-win32\n* msvc2013-win64\n* osx-carbon-i386\n* osx-cocoa-x86-64\n* posix-local\n* precise-amd64\n* precise-i386\n* setup-mingw-w64\n* setup-schroot-centos5\n* setup-schroot-centos6\n* setup-schroot-precise\n* setup-schroot-trusty\n* setup-schroot-wheezy\n* source-tarball\n* trusty-amd64\n* trusty-i386\n* update-all-schroots\n* wheezy-amd64\n* wheezy-i386", "stdout_lines": ["Usage: scripts/build.py <target> [-clean] [-debug]", "", "The supported targets are:", "* centos5-amd64", "* centos5-i386", "* centos6-amd64", "* centos6-i386", "* mingw-w64-cross-win32", "* mingw-w64-cross-win64", "* msvc-winsdk71-win32", "* msvc-winsdk71-win64", "* msvc2008-win32", "* msvc2008-win64", "* msvc2010-win32", "* msvc2010-win64", "* msvc2012-win32", "* msvc2012-win64", "* msvc2013-win32", "* msvc2013-win64", "* osx-carbon-i386", "* osx-cocoa-x86-64", "* posix-local", "* precise-amd64", "* precise-i386", "* setup-mingw-w64", "* setup-schroot-centos5", "* setup-schroot-centos6", "* setup-schroot-precise", "* setup-schroot-trusty", "* setup-schroot-wheezy", "* source-tarball", "* trusty-amd64", "* trusty-i386", "* update-all-schroots", "* wheezy-amd64", "* wheezy-i386"]}
```

It seems that you perform actions depending on the Ubuntu release, you might want to consider using the generic packages (i.e: "wkhtmltox-*_linux-generic-i386.tar.xz", files).

**Comment by steenzout** [comment]
```
wkhtmltopdf_tarball: "wkhtmltox-{{ wkhtmltopdf_version }}.tar.bz2"
wkhtmltopdf_tarball_download_url: "https://downloads.wkhtmltopdf.org/{{ wkhtmltopdf_mm_version }}/{{ wkhtmltopdf_version }}/{{ wkhtmltopdf_tarball }}"
```

this ^ is the way the role builds the URL for the tarball.

I don't see any `generic` tarball on [https://downloads.wkhtmltopdf.org/0.12/0.12.1/](https://downloads.wkhtmltopdf.org/0.12/0.12.1/); I only see the `wkhtmltox-{{ wkhtmltopdf_version }}.tar.bz2` which is what it gets downloaded.

to be honest, I never managed to compile `0.12.1` by hand on Xenial so I don't know what would be the right way to do it.
Package installation also doesn't work for `0.12.1` on Xenial (last time I tried).
I only managed to install `0.12.4` on Xenial which is not the recommended version for Odoo (based on the organizations in your profile I'm assuming this is what you want to use it for).

I don't use Xenial anywhere in production (plus I use containers for most of my stuff [steenzout/odoo](https://hub.docker.com/r/steenzout/odoo/)) so I couldn't justify spending the time on it.
if you know someone who has the right steps / instructions to build wkhtmktopdf on Xenial I'm happy to patch the role (or you can make a PR?).

**Comment by steenzout** [comment]
another alternative is to find someone who has published a `0.12.1` debian package for Xenial, create a `pre_task` to add the PPA to the server and then use `package` installation?

**Comment by steenzout** [comment]
I actually tried to help the wkhtmltopdf author to setup a build environment anyone could use to compile its packages but he refused :) https://github.com/wkhtmltopdf/wkhtmltopdf/pull/3245/files

at that point I gave up.

**Comment by steenzout** [comment]
it seems you can do a package installation: https://www.linode.com/docs/websites/cms/install-odoo-10-on-ubuntu-16-04 .

I can try this later tonight if you want and post here a work-able playbook.

let me know.

**Comment by vonpupp** [comment]
Thank you very much @steenzout. Yes, exactly I need wkhtmltopdf for Odoo purposes. To be honest I am quite new to Odoo, so I haven't had yet a properly wkhtmltopdf working on Xenial either. I was hoping I could use your playbook to avoid the nightmare hehe. As you said, 0.12.4 "should" work, but it seems to hang during installation (timeout on http://download.gna.org).

It seems so that the guide you provided uses a workaround of installing an older wkhtmltopdf Ubuntu package on Xenial, perhaps I can do my own playbook based on the supplied guide.

I am strongly considering moving to Debian for Odoo purposes. Ubuntu sucks, big time!
